### ISSUE TITLE
The statement listed below is not true for the REDUCE collection-prcessing method

### ISSUE THREAD

**Issue by keepitmovingforward** [learn-co-curriculum/js-advanced-functions-the-lost-context-bug#3]
ASIDE: This pattern works for forEach as well as map, **reduce** and all the other collection-processing methods. Consult their documentation to see where a thisArg is expected.

Just reviewed this with Ann (our Lead Instructor) and we verified that reduce does not allow for a thisArg argument. - ref:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

**Comment by sgharms** [comment]
You're absolutely right. The discussion on this topic is quite interesting.

https://stackoverflow.com/a/14913133
